### ISSUE TITLE
Error running AMST - problem with pyopencl

### ISSUE THREAD

**Issue by ChloeQuignot** [jhennies/amst#12]
Hi!

First of all, thanks for sharing your code!

It works nearly all the time without problems except in some situations when my number of input images is over approximately 2000 images (from what I can see).

The error seems to be linked to pyopencl and I was wondering if you've ever encountered this before?

```text
Traceback (most recent call last):
  File "/opt/amst/run_amst.py", line 81, in <module>
    **params
  File "/opt/amst/amst_linux/amst_main.py", line 592, in amst_align
    for task in tasks]
  File "/opt/amst/amst_linux/amst_main.py", line 592, in <listcomp>
    for task in tasks]
  File "/opt/conda/micromamba/envs/amst_env/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/conda/micromamba/envs/amst_env/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/conda/micromamba/envs/amst_env/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/amst/amst_linux/amst_main.py", line 461, in _sift_on_pair
    match = mp(keypoints_ref, keypoints_mov)
  File "/opt/conda/micromamba/envs/amst_env/lib/python3.6/site-packages/silx/opencl/sift/match.py", line 178, in match
    numpy.int32(nkp2.size))
  File "/opt/conda/micromamba/envs/amst_env/lib/python3.6/site-packages/pyopencl/__init__.py", line 840, in kernel_call
    return self._enqueue(self, queue, global_size, local_size, *args, **kwargs)
  File "<generated code>", line 119, in enqueue_knl_matching
pyopencl._cl.LogicError: clEnqueueNDRangeKernel failed: INVALID_GLOBAL_WORK_SIZE
```

I'm not an expert when it comes to using pyopencl but I've been looking into global work sizes and was wondering if adjusting the number of CPUs the job runs on so that it's a multiple of the number of images in my folder could work (for now, I run AMST on 20 CPUs with >1000 input images per sample)? Do you have any advice on this? 
The error seems to appear sporadically, and for now, I didn't really manage to find any pattern for when it comes up. All I've seen is that sometimes, when I have more than 2000 images and I reduce this number, it seems to work again but reducing the number of images isn't really a permanent solution for me.

Thanks in advance for your help,
Chloé

**Details on how I run AMST:**

1. Prealignment with snAMST

I first run a prealignment on my dataset using snAMST (commit: e66fb66) with the following parameters:
```yaml
# Workflow parameters
local_align_method : sift
# "sift" or "xcorr", in most cases SIFT is better
local_auto_mask : 10
# Automatically remove SIFT key-points which are at the edge of the actual (non-zero) data
local_norm_quantile_low : 0.01
# How to normalize the data (lower and upper bound using quantiles)
local_norm_quantile_high : 0.99

# These parameters can be used to the threshold the data before runnin the alignment. However, I currently don't
# recommend using these.
local_mask_range_low : 0
local_mask_range_high : 0
local_thresh_low : 0
local_thresh_high : 0

# Compute settings
local_device_type : CPU
# CPU is currently more efficient for the cluster
gpus : 0
# Has no effect if local_device_type=CPU
cluster : none
# Can be "none" or "slurm"
```

2. Convert 16bit to 8bit images

If images are 16bit, I change them to 8bit in python using tifffile
```python
    img16 = imread(im_file_in)
    img8 = (img16/256).astype('uint8')
    imsave(im_file_out, img8)
```

3. run AMST

Then I run AMST (commit: f94e980) with the following parameters:
```yaml
median_radius: 7             # radius of the median smoothing surrounding
coarse_alignment: 'SIFT'     # Use SIFT to get the raw data close to the template
sift_sigma: 1.6              # Pre-smooth data before running the SIFT
sift_downsample: [2, 2]      # Downsample the data for the SIFT (for speed-up, downsampling by 2 should not
                             #     compromize the final result
n_workers: 20                # Number of CPU cores allocated
n_workers_sift: 20           # Number of threads for the SIFT step (must be 1 if run on the GPU)
sift_devicetype: 'CPU'       # Run SIFT on GPU or CPU
compute_range: 'np.s_[:]'    # Select a subset of the data for alignment (good for parameter testing)
verbose: False               # Set to True for a more detailed console output
write_intermediates: False   # Set to True to also write the median smoothed template and the results of the SIFT
                             # step to disk; two folders will be created within the specified target directory that
                             # contain this data ('refs' and 'sift')
elastix_params:
        # These are copied from the default affine parameter file:
        # http://elastix.bigr.nl/wiki/images/c/c5/Parameters_Affine.txt
        FixedInternalImagePixelType: "float"
        MovingInternalImagePixelType: "float"
        UseDirectionCosines: True
        # **************** Main Components **************************
        Registration: "MultiResolutionRegistration"
        Interpolator: "BSplineInterpolator"
        ResampleInterpolator: "FinalBSplineInterpolator"
        Resampler: "DefaultResampler"
        FixedImagePyramid: "FixedRecursiveImagePyramid"
        MovingImagePyramid: "MovingRecursiveImagePyramid"
        Optimizer: "AdaptiveStochasticGradientDescent"
        Transform: "AffineTransform"
        Metric: "AdvancedMattesMutualInformation"
        # ***************** Transformation **************************
        AutomaticScalesEstimation: False # For some reason turning this off really improves the result
        AutomaticTransformInitialization: True
        HowToCombineTransforms: "Compose"
        # ******************* Similarity measure *********************
        NumberOfHistogramBins: 32
        ErodeMask: False
        # ******************** Multiresolution **********************
        NumberOfResolutions: 3 # For speed up we compromise one resolution level
        ImagePyramidSchedule: [8, 8, 3, 3, 1, 1]
        # ******************* Optimizer ****************************
        MaximumNumberOfIterations: 200 # Increasing this yields more robustness, but takes more time
        MaximumStepLength: [4, 2, 1]
        # **************** Image sampling **********************
        NumberOfSpatialSamples: 2048
        NewSamplesEveryIteration: True
        ImageSampler: "RandomCoordinate"
        # ************* Interpolation and Resampling ****************
        BSplineInterpolationOrder: 1
        FinalBSplineInterpolationOrder: 3
        DefaultPixelValue: 0
        WriteResultImage: True
        ResultImagePixelType: "short"
        ResultImageFormat: "mhd"
```
